### ISSUE TITLE
Error during scaffolding process 

### ISSUE THREAD

**Issue by arturmiglio** [reintroducing/generator-threshold#4]
I get an error during the scaffolding process. See the complete error below:

```
? Project name XXXX
? Project description
? Project Git repo XXXX
? Your name Artur Miglio
? Your email XXXX
? Your site URL XXXX
? ECMAScript version? ES5
? Use Browserify? (Required if ES >= 6) Yes
? Use jQuery? Yes
? Use Backbone? (Includes jQuery) Yes
? Use React? No
? Use CSS sprites? Yes
? Use icon font? Yes
? Use JPEGmini during image minification? Yes
```

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
AssertionError: Trying to copy from a source that does not exist: /Users/arturmiglio/.nvm/versions/node/v5.10.0/lib/node_modules/generator-threshold/app/templates/.gitignore
    at EditionInterface.exports._copySingle (/Users/arturmiglio/.nvm/versions/node/v5.10.0/lib/node_modules/generator-threshold/node_modules/mem-fs-editor/lib/actions/copy.js:45:3)
    at EditionInterface.exports.copy (/Users/arturmiglio/.nvm/versions/node/v5.10.0/lib/node_modules/generator-threshold/node_modules/mem-fs-editor/lib/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/arturmiglio/.nvm/versions/node/v5.10.0/lib/node_modules/generator-threshold/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:10:8)
    at module.exports.generators.Base.extend.writing (/Users/arturmiglio/.nvm/versions/node/v5.10.0/lib/node_modules/generator-threshold/app/index.js:160:17)
    at /Users/arturmiglio/.nvm/versions/node/v5.10.0/lib/node_modules/generator-threshold/node_modules/yeoman-generator/lib/base.js:429:16
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

**Comment by reintroducing** [comment]
I apologize but this is no longer maintained. :\  PRs for fixes are still welcome, however.
